tienda_online/carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar',views.add, name="add"),
    path('eliminar', views.remove, name='remove')
]

tienda_online/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address')

]

tienda_online/shipping_address/urls.py
from django.urls import path

from . import views

app_name = 'shipping_addresses'

urlpatterns = [
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('crear', views.create, name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path("default/<int:pk>",views.default, name='default')

]

tienda_online/tienda_online/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from products.views import ProductListView

#las dos librerias siguientes son para enlazar las imagenes a las urls

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('',ProductListView.as_view(), name='index'),
    path('usuarios/login',views.login_view, name='login'),
    path('usuarios/logout',views.logout_view, name='logout'),
    path('usuarios/registro',views.register, name='register'),
    path('admin/', admin.site.urls),

    path('product/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_address.urls')),
]

if settings.DEBUG: #ESTA CONDICION NOS PERMITIRÁ MOSTRAR LAS IMAGENES EN NUESTRO TEMPLATE
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tienda_online/orders/models.py
import uuid
from enum import Enum

from django.db import models
from carts.models import Cart
from users.models import User
from shipping_address.models import ShippingAddress

from django.db.models.signals import pre_save


class OrderStatus(Enum):
    CREATED = 'CREATED'
    PAYED = 'PAYED'
    COMPLETED = 'COMPLETED'
    CANCELED = 'CANCELED'

choices = [(tag, tag.value) for tag in OrderStatus]    

class Order (models.Model):
    order_id = models.CharField(max_length=100, null=False, blank=False, unique=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.CharField(max_length= 50, choices=choices, default=OrderStatus.CREATED)

    shipping_total = models.DecimalField(default=20, max_digits=8 , decimal_places=2)
    total = models.DecimalField(default=5, decimal_places=2,max_digits=8)
    created_at = models.DateTimeField(auto_now_add=True)
    shipping_address = models.ForeignKey(ShippingAddress, null=True, blank=True, on_delete=models.CASCADE)


    def __str__(self):
        return self.order_id 

    def get_or_set_shipping_address(self):
        if self.shipping_address:
            return self.shipping_address

        shipping_address = self.user.shipping_address
        if shipping_address:
            self.update_shipping_address(shipping_address)

        return shipping_address   

    def update_shipping_address(self, shipping_address):
        self.shipping_address = shipping_address
        self.save()         

    def update_total(self):
        self.total = self.get_total()
        self.save() 
    
    
    def get_total(self):
        return self.cart.total + self.shipping_total
    



def set_order_id(sender,instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = str(uuid.uuid4())


def set_total(sender, instance, *args, **kwargs):
    instance.total = instance.get_total()

pre_save.connect(set_order_id, sender=Order)
pre_save.connect(set_total, sender= Order)

tienda_online/orders/views.py
from django.shortcuts import render,redirect,get_object_or_404
from carts.utils import get_or_create_cart
from .utils import get_or_create_order, breadcrumb

from django.contrib.auth.decorators import login_required
 
from shipping_address.models import ShippingAddress




#permite restringir vistas para usuarios autenticados
@login_required(login_url='login')
def order(request):
    cart = get_or_create_cart(request)
    
    order = get_or_create_order(cart, request)
    print(order.order_id)
    context = {'order': order,
               'cart' : cart,
               'breadcrumb':breadcrumb()    
                }
    return render(request, 'orders/order.html', context)

@login_required(login_url = 'login')
def address(request):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)
    shipping_address = order.get_or_set_shipping_address()
    hay_opciones = request.user.shippingaddress_set.count() > 1

    context = {
        'cart':cart,
        'order':order,
        'shipping_address':shipping_address,
        'breadcrumb':breadcrumb(address=True),
        'hay_opciones':hay_opciones
    }

    return render(request, 'orders/address.html', context)


@login_required(login_url = 'login')
def select_address(request):
    shipping_addresses = request.user.shippingaddress_set.all()
    
    context = {
        'breadcrumb':breadcrumb(address=True),
        'shipping_addresses':shipping_addresses,
        
    }
    return render(request, 'orders/select_address.html',context)    
    
@login_required(login_url = 'login')
def check_address(request,pk):    
        cart = get_or_create_cart(request)
        order = get_or_create_order(cart, request)

        shipping_address = get_object_or_404(ShippingAddress, pk=pk)
        if request.user.id != shipping_address.user_id:
            return redirect('carts:cart')

        order.update_shipping_address(shipping_address)

        return redirect('orders:address')    

tienda_online/orders/templates/orders/address.html
{% extends 'base.html' %}

{% block breadcrumb %}

    {% include 'orders/snippets/breadcrumb.html' %}

{% endblock breadcrumb %}



{% block content %}

<div class="col">
    {% if shipping_address %}
        <div class="h3">
            Enviar pedido a punto de entrega
        </div>
        <div class="">
            {% include 'shipping_addresses/snippets/shipping_address.html' %}

            {% if hay_opciones %}
                <div class="mt-2 btn btn-warning">
                    <a href="{% url 'orders:select_address' %}">Elegir direccion diferente</a>
                </div>    
            {% endif %}   
            
        </div>
    {% else %} 
        <div class="h3">
            Registra tu direccción de envío
        </div>
        <div class="">
            {% url 'orders:address' as next_url %}
            <a href="{% url 'shipping_addresses:create' %}?next={{ next_url }}">Nueva dirección de envío</a>
        </div>
    
    {% endif %}

</div>

{% endblock content %}

tienda_online/orders/templates/orders/order.html
{% extends 'base.html' %}

 
{% block breadcrumb %}

    {% include 'orders/snippets/breadcrumb.html' %}

{% endblock breadcrumb %}


{% block content %}

<div class="col-8">
    <div class="h3">
        
        revisa tu pedido

    </div>
    <div class="card mt-3">
        <div class="card-body">
            {% for product in cart.products.all %}
            
            {% include 'orders/snippets/product.html' %}

            {% endfor %}
        </div>
    </div>
</div>
<div class="col mt-5">

    {%include 'orders/snippets/resume.html'%}

</div>

{% endblock content %}

tienda_online/orders/templates/orders/select_address.html
{% extends 'base.html' %}

{% block breadcrumb %}
    {% include 'orders/snippets/breadcrumb.html' %}
{% endblock breadcrumb %}


{% block content %}
<div class="col">
    <div class="h3">
        Selecciona una dirección de envío
    </div>
    <div class="mt-2">
        {% for shipping_address in shipping_addresses %}
            <div class="card mb-2">
              <div class="card-body">
                <h5 class="card-title">{{ shipping_address.address}}</h5>
                <p class="card-title">{{ shipping_address.postal_code}}</p>
                <a href="{% url 'orders:check_address' shipping_address.pk %}" class="btn btn-warning">Seleccionar</a>
              </div>
            </div>  
        {% endfor %}
    </div>
</div>    
{% endblock content %}