tienda_online/carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar',views.add, name="add"),
    path('eliminar', views.remove, name='remove')
]

tienda_online/products/urls.py
from django.urls import path

from .views import ProductDetailView,ProductSearchListView

#genero esta variable para que en un futuro no existan choques entre rutas de igual nombre pero de  distita app
app_name = 'products'
#las rutas de esta app se escriben {%url 'products:name'%}

urlpatterns = [
    path('search', ProductSearchListView.as_view(), name='search'),
    path('<slug:slug>',ProductDetailView.as_view(), name='product' )
]

tienda_online/tienda_online/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from products.views import ProductListView

#las dos librerias siguientes son para enlazar las imagenes a las urls

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('',ProductListView.as_view(), name='index'),
    path('usuarios/login',views.login_view, name='login'),
    path('usuarios/logout',views.logout_view, name='logout'),
    path('usuarios/registro',views.register, name='register'),
    path('admin/', admin.site.urls),

    path('product/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_address.urls')),
]

if settings.DEBUG: #ESTA CONDICION NOS PERMITIRÁ MOSTRAR LAS IMAGENES EN NUESTRO TEMPLATE
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tienda_online/products/models.py
import uuid #libreria para generar ids aleatorios

from django.db import models
from django.utils.text import slugify

from django.db.models.signals import pre_save

class Product(models.Model):
    title =  models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    model = models.CharField(max_length= 20)
    image = models.ImageField(upload_to='products/',blank=False, null=False)
    slug = models.SlugField(unique=True, blank=False, null= False)
    created_at = models.DateTimeField(auto_now_add=True)

    
    #método para generar slug automáticos
    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.title)
    #     super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.title
    

# función que genera slug a través de callback que cumple la misma función que el método save() de Product
def set_slug(sender, instance, *args, **kwargs):
    if instance.title and not instance.slug: 
        
        slug = slugify(instance.title) #genera el slug a partir del título

        while Product.objects.filter(slug= slug).exists(): #si el titulo está repetido genero uno con id aleatorio

            slug = slugify('{}-{}'.format(instance.title,str(uuid.uuid4())[:8]))

        instance.slug = slug    
pre_save.connect(set_slug, sender=Product)    

tienda_online/products/views.py
from django.shortcuts import render

from django.db.models import Q #permite ejecutar una consulta aplicando diferentes filtros

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Product

class ProductListView(ListView):
    
    template_name = "index.html"
    queryset = Product.objects.all().order_by('price')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Listado de productos'
        context['products'] = context['product_list'] #la variable context contiene la peticion con los productos

        print(context)
        return context

class ProductDetailView(DetailView):
    model = Product
    template_name = "products/product.html"

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        print(context)
        return context

class ProductSearchListView(ListView):
    template_name = 'products/search.html'

    def get_queryset(self):
        #aquí utilizo la clase Q para generar un filtro similar a JOIN SQL

        filters = Q(title__icontains=self.query()) | Q(category__title__icontains=self.query())
        return Product.objects.filter(filters)

    def query(self):
        return self.request.GET.get('q')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.query()
        context['count'] = context['product_list'].count()
        
        return context

    

tienda_online/products/templates/products/snippets/list.html
<div class="row">
    {% for product in products %}
        
           {% include 'products/snippets/product.html'%} 
        
    {%endfor%}
</div>

tienda_online/products/templates/products/snippets/product.html
<div class="col-3 mt-5">
    <div class = "card h-100">
        {% if product.image %}
            <img src = "{{ product.image.url}}" alt = "imagen del producto" height = "200">
        {% endif %}
        <div class = "card-body">
            <h5 class = "card-title">{{product.title}}</h5>
            <p class = "card-text">{{product.description}}</p>
            <a href = "{% url 'products:product' product.slug %}" class = "btn btn-primary">Detalles</a>
        </div>
    </div>
</div>


                    {% comment %} <li class="list-group-item">
                        {{product.title}} 
                        {{product.price}}  {% endcomment %}
                        {% comment %} {% if product.stock %}
                        <span class="text-success">Disponible</span>
                        {% else %}
                        <span class="text-danger">No disponible</span>
                        {% endif %}
                         {% endcomment %}
                      

tienda_online/products/templates/products/snippets/search.html
<form action = "{% url 'products:search' %}">
    <div class="input-group" >
        <input type="text" name="q" value="{{ query }}" class="form-control" placeholder="Buscar">
        <div class="input-group-append">
            <input type="submit" name="" value="Buscar" class="btn btn-primary">
        </div>
    </div>
</form>