tienda_online/carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar',views.add, name="add"),
    path('eliminar', views.remove, name='remove')
]

tienda_online/shipping_address/urls.py
from django.urls import path

from . import views

app_name = 'shipping_addresses'

urlpatterns = [
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('crear', views.create, name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path("default/<int:pk>",views.default, name='default')

]

tienda_online/tienda_online/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from products.views import ProductListView

#las dos librerias siguientes son para enlazar las imagenes a las urls

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('',ProductListView.as_view(), name='index'),
    path('usuarios/login',views.login_view, name='login'),
    path('usuarios/logout',views.logout_view, name='logout'),
    path('usuarios/registro',views.register, name='register'),
    path('admin/', admin.site.urls),

    path('product/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_address.urls')),
]

if settings.DEBUG: #ESTA CONDICION NOS PERMITIRÁ MOSTRAR LAS IMAGENES EN NUESTRO TEMPLATE
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tienda_online/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> 
            {% block title %}
            {% endblock title %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>
    {% include 'navbar.html' %}

   <div class="container">

    {% block breadcrumb %}
    {% endblock breadcrumb %}
    <div class="row mt-4">

 

        {% block content %}
        
        {% endblock content %}

     </div>
   </div>
</body>
<script src="https://kit.fontawesome.com/82f0ea754b.js" crossorigin="anonymous"></script>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% block extraJs %}

{% endblock extraJs %}
</html>

tienda_online/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{title}}
{% endblock title %}

{% block content %}
 {% include 'messages.html' %}

    
   
        <div class="col">
            <h1 class="text-center">{{ message }}</h1>
            {% include 'products/snippets/search.html' %}

            {% include 'products/snippets/list.html' %}
        </div>

{% endblock content %}

{% block extraJs %}

<script src = "{% static 'js/main.js' %}"></script>

{% endblock extraJs %}

tienda_online/templates/messages.html
{% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <div class= "alert alert-success">
                    <button type = "button" class = "close" data-dismiss = "alert">x</button>
                    {{message}}
                </div>
                
            {% endif %}
        
        {% endfor %}
    {% endif %}

tienda_online/templates/navbar.html
{% comment 'primero' %}
urls que condicionan el estado "active" de la barra de navegación
{% endcomment %}

{% url 'login' as login %}
{% url 'register' as register %}
{% url 'logout' as logout %} 
{% url 'carts:cart' as cart %}
{% url 'shipping_addresses:shipping_addresses' as shipping_addresses %}



<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a href="{% url 'index' %}" class="navbar-brand">DomoticsStore</a>

    <button type="button" name="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navb">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navb" class="navbar-collapse collapse hide">
        
        
        <ul class="navbar-nav">
            <li class="nav-item {% if request.path == cart%}active{% endif%}">
                <a class="nav-link" href="{{cart}}">
                    
                    mi carrito <span class="fas fa-shopping-cart"></span>

                </a>
            </li>
        </ul>

        {% if user.is_authenticated %}
        <ul class="navbar-nav">
            <li class="nav-item {% if request.path == shipping_addresses%}active{% endif%}">
                <a class="nav-link" href="{{shipping_addresses}}">
                    
                    Mis direcciones <span class="fas fa-map-marker-alt"></span>

                </a>
            </li>
        </ul>
        {% endif %}
        
        <ul class="nav navbar-nav ml-auto">   
            {% if user.is_authenticated %}
            
                <li class="navbar-item ">
                    <a href="{{logout}}" class="nav-link">
                        <span class="fas fa-sign-in-alt"></span>
                        Logout</a>            
                </li>

            {% else %}

                <li class="navbar-item {% if request.path == login %}active{% endif %}">
                    <a href="{{login}}" class="nav-link">
                        <span class="fas fa-user"></span>
                        Login</a>
                </li>

                <li class="navbar-item {% if request.path == register %}active{% endif %}">
                    <a href="{{register}}" class="nav-link">
                        <span class="fas fa-user"></span>
                    registro</a>
                </li>

            {% endif %}
        </ul>


    </div>
</nav>