tienda_online/carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar',views.add, name="add"),
    path('eliminar', views.remove, name='remove')
]

tienda_online/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address')

]

tienda_online/products/urls.py
from django.urls import path

from .views import ProductDetailView,ProductSearchListView

#genero esta variable para que en un futuro no existan choques entre rutas de igual nombre pero de  distita app
app_name = 'products'
#las rutas de esta app se escriben {%url 'products:name'%}

urlpatterns = [
    path('search', ProductSearchListView.as_view(), name='search'),
    path('<slug:slug>',ProductDetailView.as_view(), name='product' )
]

tienda_online/tienda_online/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from products.views import ProductListView

#las dos librerias siguientes son para enlazar las imagenes a las urls

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('',ProductListView.as_view(), name='index'),
    path('usuarios/login',views.login_view, name='login'),
    path('usuarios/logout',views.logout_view, name='logout'),
    path('usuarios/registro',views.register, name='register'),
    path('admin/', admin.site.urls),

    path('product/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_address.urls')),
]

if settings.DEBUG: #ESTA CONDICION NOS PERMITIRÁ MOSTRAR LAS IMAGENES EN NUESTRO TEMPLATE
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tienda_online/carts/models.py
import uuid
import decimal
from django.db import models
from users.models import User
from products.models import Product

from django.db.models.signals import pre_save, post_save
from django.db.models.signals import m2m_changed


class Cart(models.Model):
    cart_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    products = models.ManyToManyField(Product, through='CartProducts')
    subtotal = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    FEE = 0.21

    def __str__(self):
        return self.cart_id

    def update_totals(self):
        self.update_subtotal()
        self.update_total()
        #me conecto con el modelo Order a través de la relación uno a muchos como sigue:
        if self.order:
            self.order.update_total()

    def update_subtotal(self):
        self.subtotal = sum([
            #calculo el subtotal de toda la lista de productos teniendo en cuenta la cantidad de cada producto
            cp.quantity * cp.product.price for cp in self.products_related()
         
         ])
        self.save()

    def update_total(self):
        self.total = self.subtotal +  (self.subtotal * decimal.Decimal(Cart.FEE)) 
        self.save()  

    #método para evitar el problema de n +1 query. utilizo el metodo select_related
    #esto obtiene todos los objetos CartProducts y Products en una sola linea de código.
    def products_related(self):
        return self.cartproducts_set.select_related('product')    


    #defino un property para centralizar la obtencion de una orden con respecto a un carrito
    @property
    def order(self):
        return self.order_set.first()




class CartProductManager(models.Manager):
    #método para extender al objeto objects en views.add()

    def create_or_update_quantity(self, cart, product, quantity=1):
        object, created = self.get_or_create(cart=cart, product=product)

        if not created:
            quantity = object.quantity + quantity

        object.update_quantity(quantity) 
        return object


class CartProducts(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    
    objects = CartProductManager()

    def update_quantity(self, quantity=1):
        self.quantity = quantity
        self.save()


#implemento un callback para asignar el cart_id

def set_cart_id(sender, instance, *args, **kwargs):
    if not instance.cart_id:
        instance.cart_id = str(uuid.uuid4())  #si no hay un id lo genera a través de la clase uuid

pre_save.connect(set_cart_id,sender=Cart)


#callback para mantener el total del precio del carrito siempre actualizado

def update_totals(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        instance.update_totals()

m2m_changed.connect(update_totals, sender=Cart.products.through)        

#callback para los objetos de tipo CartProducts 
def post_save_update_totals(sender, instance, *args, **kwargs):
    instance.cart.update_totals()

post_save.connect(post_save_update_totals, sender = CartProducts)

tienda_online/carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cart,CartProducts
from .utils import get_or_create_cart
from products.models import Product


def cart(request):
    
    cart = get_or_create_cart(request)    
    
    context = {
        'cart':cart
    }
    return render(request, 'carts/cart.html', context)


def add(request):
    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))
    quantity = int(request.POST.get('quantity',1)) #levanto la cantidad del form y por defecto le asigno 1
    
    cart_product = CartProducts.objects.create_or_update_quantity(cart=cart,
                                                                  product=product,
                                                                  quantity=quantity
                                                                )

    # cart.products.add(product, through_defaults={'quantity':quantity})
    context = {
        'cart_product': cart_product,
        'quantity': quantity,
        'product':product
    }   

    return render(request, 'carts/add.html',context)

def remove(request):
    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))
    
    cart.products.remove(product)

    return redirect('carts:cart')

    
        

tienda_online/carts/templates/carts/add.html
{% extends 'base.html' %}
{% load product_extras %}
{% load cart_extras %}

{% block content %}
<div class="col-3">
    {% if product.image %}
        <img src="{{product.image.url}}" alt="imagen del producto" width="200">
    {%else%}
        <h4 class="font-weight-red">el producto no tiene imagen</h4>  
    {%endif%}
</div>
<div class="col">
    <div class="h3 font-weight-bold text-success">
         {{ quantity | quantity_add_format }} al carrito{# filter de cart_extras #} 
    </div>
    <div class="">
        <a href="{% url 'products:product' product.slug %}">
            {{product.title}}
        </a>
    </div>
    <div class="font-weight-bold text-danger">
        {{product.price | price_format }} {# aquí hago uso del filtro implementado en products/templatetags  #} 
    </div>
    <div>
        <a href="{% url 'index' %}" class="font-weight-bold text-black">agregar más productos</a>
    </div>

</div>


{% endblock content %}

tienda_online/carts/templates/carts/cart.html
{% extends 'base.html' %}

{% block content %}

{% load product_extras %}

{% if cart.products.exists %}

<div class="col-8">
    <table class="table">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for cp in cart.products_related %}
                {% with product=cp.product  %}
                    <tr>
                        <th>{{ forloop.counter }}</th>
                        <th>
                            {% if product.image %}
                            <img src="{{ product.image.url }}" alt="imagen del producto" width="50" height="50">
                            {% endif %}
                        </th>
                        <th>
                            <a href="{% url 'products:product' product.slug %}">{{product.title}}</a>
                            {% include 'carts/snippets/remove.html' %}
                        </th>
                        <th>
                            {{cp.quantity}}
                        </th>
                        <th>
                            <span class="font-wieght-bold text-danger">{{product.price | price_format}}</span>
                        </th>
                    </tr>
                {% endwith %}
            {% endfor %}    
                
        </tbody>

    </table>
</div>
<div class="col">
    <div class="card">
        <div class="card-body">
        <div class="font-wieght-bold">
            Subtotal({{ cart.products.count }}): <span class="text-danger">{{cart.subtotal | price_format }}</span>
        </div>
        <div class="mt-2">
            <a href="{% url 'orders:order' %}" class="btn btn-warning">Comprar</a>
        </div>
        </div>
    </div>
</div>

{%else%}
<div class="col-3">
    <p class="h3 text-warning">Carrito sin productos</p>
    <a href="{% url 'index' %}">Ver productos</a>
</div>
{% endif %}
{% endblock content %}